### PR TITLE
Add --no-cache-dir for pip to disable pip installation caching

### PR DESCRIPTION
**Pull request by vzavalskyi**
Hello,

I'm just starting to explore TTS gen AI, and your project is a great starting point. Thank you!

I've noticed that starting the project with Docker Compose takes some time, particularly due to downloading the main image ghcr.io/rsxdalv/tts-generation-webui:main, which currently is 28.4GB.

This PR aims to reduce the image size by disabling the pip cache, which is only used during installation (pip install command).

By disabling the cache, we can achieve a reduction of around 6GB in size.
Example:
```bash
$ docker images
REPOSITORY                             TAG            IMAGE ID       CREATED             SIZE
tts-generation-webui                   no-cache-dir   9a5456cca69b   About an hour ago   22GB    # improved version
ghcr.io/rsxdalv/tts-generation-webui   main           68b06fd3bd49   24 hours ago        28.4GB # original image
```

More information about pip cache:
- https://pip.pypa.io/en/stable/topics/caching/#disabling-caching

Please contact me if you have any questions. 

Thank you!

### CODE REVIEW

**Comment by rsxdalv** [comment]
Thank you!

I would like to ask about cache dir in the case of multiple requirements files: if requirements_a.txt installs zzz==1.2.3 and requirements_b.txt installs zzz=1.2.4 and requirements_c.txt installs zzz==1.2.3 is there that small performance hit?

Normally such a thing should not happen but that's 50% of the reason we have multiple requirements files due to python's dependency extravaganza.

If so, I am thinking about a `pipenv --clear` option at the end instead.

Either way, excellent work. Having smaller container images will help me as much as others.

I am rebuilding the installer right now so I won't immediately merge this because it would create a merge conflict, but I think we should be good to merge soon!

**Comment by rsxdalv** [comment]
And as for the size, I know that a conda install with cleared cache was below 20gb, so perhaps there's still potential for some space savings!

**Comment by vzavalskyi** [comment]
Hello @rsxdalv 

I did an investigation regarding the cache directory and here are the findings:

```bash
$ docker run -it --rm ghcr.io/rsxdalv/tts-generation-webui:main bash
root@5108bfc52de5:/app/tts-generation-webui# du -h --max-depth=8 / 2> /dev/null| awk '$1 ~ /[0-9.]+G/'
4.8G    /usr/local/cuda-11.8/targets/x86_64-linux/lib
4.8G    /usr/local/cuda-11.8/targets/x86_64-linux
4.8G    /usr/local/cuda-11.8/targets
5.2G    /usr/local/cuda-11.8
5.2G    /usr/local
1.2G    /usr/lib
6.5G    /usr
1.1G    /root/.cache/pip/http-v2/6
1.2G    /root/.cache/pip/http-v2/3
5.9G    /root/.cache/pip/http-v2
6.0G    /root/.cache/pip
6.1G    /root/.cache
6.4G    /root
1.1G    /venv/lib/python3.10/site-packages/nvidia/cublas/lib
1.1G    /venv/lib/python3.10/site-packages/nvidia/cublas
3.7G    /venv/lib/python3.10/site-packages/nvidia
1.2G    /venv/lib/python3.10/site-packages/torch/lib
1.3G    /venv/lib/python3.10/site-packages/torch
8.8G    /venv/lib/python3.10/site-packages
8.8G    /venv/lib/python3.10
8.8G    /venv/lib
8.8G    /venv
24G     /
```
It appears that the only files we can safely remove are related to the pip cache. Other files belong to various libraries and might be required during runtime.

Regarding the alternative command, I think in our case we should use `pip cache purge`, right?

```bash
root@5108bfc52de5:/app/tts-generation-webui# pip cache purge
Files removed: 2343
root@5108bfc52de5:/app/tts-generation-webui# du -sh /root/.cache/*
55M     /root/.cache/node-gyp
25M     /root/.cache/pip
```
According to my experiments, the result is the same as disabling the pip cache. I was considering this change but decided to keep the number of layers smaller. However, using `pip cache purge` might be more convenient for development.

I can implement this change if you think it's a better approach. Please let me know your thoughts.

Thank you!

**Comment by vzavalskyi** [comment]
Regarding the cache directory and the case of multiple requirements files (e.g., requirements_a.txt installs zzz==1.2.3, requirements_b.txt installs zzz==1.2.4, and requirements_c.txt installs zzz==1.2.3), yes, this would be a bit less efficient during the build because of the absence of a shared cache.

Additionally, regarding Docker, I was considering leveraging Docker cache to speed up builds. However, due to the nature of how Docker handles cache for `RUN` instructions, it may not be suitable. The cache for RUN instructions isn't automatically invalidated between builds. You can read more about it [here](https://docs.docker.com/build/cache/invalidation/#run-instructions).

So regarding the current Dockerfile setup where we have "RUN git clone https://github.com/rsxdalv/tts-generation-webui.git", it's important to understand that subsequent builds in case of a docker cache hit won't automatically update the cloned repository unless a layer before it changes. A potential fix for this is to use the local repository with Dockerfile `CP` command..

Thanks

**Comment by rsxdalv** [comment]
Well researched! I think we can make that change later if it seems better.
I merged these changes so that we can continue on top of this as needed. This repository is still far from requiring a 'beautiful' git history.

As for the cache - I might get burned with this but as far as I remember the github jobs don't typically cache. (One reason being - it is extra, a lot of extra storage that they would need to host). Although I vaguely remember that it is something that can be enabled but there are strict quotas.

What I think should be a fairly straightforward solution would be to make a base image that installs python/node/torch and the repo + requirements being an image that is rebuilt actively. The base image would be pushed to a docker repository acting as a cache. Of course, I have seen this go wrong so ultimately I prefer a cached and properly invalidated docker build.

**Pull request merged**
